base: api.pwa-bspackage.ddev.site
baseVariants: {  }
errorHandling: {  }
languages:
  -
    languageId: '0'
    title: English
    navigationTitle: English
    base: /
    locale: en_US.UTF8
    iso-639-1: en
    hreflang: en-US
    direction: ltr
    typo3Language: default
    flag: us
    enabled: true
rootPageId: 1
routes: {  }
